### ISSUE TITLE
RangeError: out of range index.

### ISSUE THREAD

**Issue by vainly** [socketio/socket.io-client#1002]
```E:\Workspace\artisan\artisan_server\node_modules\engine.io-client\node_modules\ws\lib\Receiver.js:386
    default: srcBuffer.copy(dstBuffer, dstOffset, 0, length); break;
                       ^

RangeError: out of range index
    at RangeError (native)
    at fastCopy (E:\Workspace\artisan\artisan_server\node_modules\engine.io-client\node_modules\ws\lib\Receiver.js:386:24)
    at Receiver.add (E:\Workspace\artisan\artisan_server\node_modules\engine.io-client\node_modules\ws\lib\Receiver.js:86:3)
    at Socket.realHandler (E:\Workspace\artisan\artisan_server\node_modules\engine.io-client\node_modules\ws\lib\WebSocket.js:800:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```
Not really sure what this means or how to fix, or where the problem is actually.

socket.io-redis dependent engine.io-client@1.5.4,  engine.io-client dependent ws@0.8.0.

windows 7, node version 6.6.0, socket.io-client 1.3.7

update socket.io-client and socket.io version to 1.5.0 fix it.
please close it. Thanks

**Comment by darrachequesne** [comment]
Closing this now, as this seems to be fixed.

Related: https://github.com/websockets/ws/issues/778
