### ISSUE TITLE
[Bug] install error - TypeError: toMap.startsWith is not a function

### ISSUE THREAD

**Issue by lmj0011** [socketio/socket.io-client#1028]
### I want to:

* report a *bug*

### Current behaviour
installing socket.io-client@1.6.0 via jspm throws error

### Steps to reproduce (if the current behaviour is a bug)
install with jspm v0.16.39

```sh
landan@lj-desktop:~/www/client1/SAELive-Clerk$ jspm install npm:socket.io-client
     Looking up npm:socket.io-client
     Updating registry cache...
     Downloading npm:socket.io-client@1.6.0
     Looking up npm:backo2
     Looking up npm:component-bind
     Looking up npm:component-emitter
     Looking up npm:debug
     Looking up npm:engine.io-client
     Looking up npm:has-binary
     Looking up npm:indexof
     Looking up npm:object-component
     Looking up npm:parseuri
     Looking up npm:socket.io-parser
     Looking up npm:to-array
     Downloading npm:debug@2.3.3
     Looking up npm:ms
     Downloading npm:socket.io-parser@2.3.1
     Looking up npm:json3
     Looking up npm:isarray
     Downloading npm:parseuri@0.0.5
     Looking up npm:better-assert
     Downloading npm:engine.io-client@1.8.0
     Looking up npm:component-inherit
     Looking up npm:engine.io-parser
     Looking up npm:has-cors
     Looking up npm:parsejson
     Looking up npm:parseqs
     Looking up npm:yeast
     Downloading npm:ms@0.7.2

err  TypeError: toMap.startsWith is not a function
         at applyMap (/home/landan/www/client1/SAELive-Clerk/node_modules/jspm/lib/build.js:251:15)
         at /home/landan/www/client1/SAELive-Clerk/node_modules/jspm/lib/build.js:527:30
         at RegExp.[Symbol.replace] (native)
         at RegExp.[Symbol.replace] (native)
         at String.replace (native)
         at /home/landan/www/client1/SAELive-Clerk/node_modules/jspm/lib/build.js:524:31
         at tryCatch (/home/landan/www/client1/SAELive-Clerk/node_modules/rsvp/dist/rsvp.js:538:12)
         at invokeCallback (/home/landan/www/client1/SAELive-Clerk/node_modules/rsvp/dist/rsvp.js:553:13)
         at publish (/home/landan/www/client1/SAELive-Clerk/node_modules/rsvp/dist/rsvp.js:521:7)
         at flush (/home/landan/www/client1/SAELive-Clerk/node_modules/rsvp/dist/rsvp.js:2373:5)
         at _combinedTickCallback (internal/process/next_tick.js:67:7)
         at process._tickCallback (internal/process/next_tick.js:98:9)

warn Installation changes not saved.
```

### Setup
- OS: Xubuntu 16.01 Linux
- browser: NA
- socket.io version: 1.6.0

**Comment by darrachequesne** [comment]
Hi! Was it working with previous version, and the same setup?

Could you please share your package.json/config.js files?

**Comment by lmj0011** [comment]
I'm starting fresh with my project, I will post more info if I'm able to reproduce

**Comment by lmj0011** [comment]
this can be closed, I wasn't able to produce. Will make another issue if something else arises.

**Comment by ecdavis15** [comment]
What did you do between this issue existing and this issue not existing? I'm seeing this issue when running with jspm version 0.15.7. I'm not sure why it's there
