### ISSUE TITLE
Use of const in strict mode

### ISSUE THREAD

**Issue by AlaDyn172** [socketio/socket.io-client#1115]
ERROR I RECEIVE:

> /var/Bot/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/index.js:9
const WebSocket = require('./lib/WebSocket');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Server.init (/var/Bot/node_modules/socket.io/node_modules/engine.io/lib/server.js:119:16)
    at new Server (/var/Bot/node_modules/socket.io/node_modules/engine.io/lib/server.js:65:8)
    at Function.attach (/var/Bot/node_modules/socket.io/node_modules/engine.io/lib/engine.io.js:123:16)
    at /var/Bot/node_modules/socket.io/lib/index.js:258:23

Please help me!

**Comment by darrachequesne** [comment]
Hi @AlaDyn172, which version of nodeJS are you running? (support for 0.10 / 0.12 was dropped in 2.x version)

**Comment by AlaDyn172** [comment]
I had 0.10 I think, but I've updated to v7, now works.
