### ISSUE TITLE
xhr poll error when sending unicode

### ISSUE THREAD

**Issue by mastasky** [socketio/socket.io-client#1151]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
Socket.io-client stops when sending a string with German Umlauts, throws xhr poll error.

### Steps to reproduce (if the current behaviour is a bug)

- Open a connection to a server
- Send a message with data object {"mid": "123", "text": "Meine zehn Brüder essen zweihundert Kuchen"}
- System won't send it, throw xhr poll error

### Expected behaviour
System should send the string like any other. Works when downgrading to in 1.7.4

### Setup
- OS: Ubuntu 16.06
- browser: irrelevant (using client from within nodeJS server app)
- socket.io version: 2.0.3 fails

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

```
Error:  Error: xhr post error
    at XHR.Transport.onError (/mnt/c/Users/Phil/Source/Repos/cai-nlptools/node_modules/engine.io-client/lib/transport.js:64:13)
    at Request.<anonymous> (/mnt/c/Users/Phil/Source/Repos/cai-nlptools/node_modules/engine.io-client/lib/transports/polling-xhr.js:109:10)
    at Request.Emitter.emit (/mnt/c/Users/Phil/Source/Repos/cai-nlptools/node_modules/component-emitter/index.js:133:20)
    at Request.onError (/mnt/c/Users/Phil/Source/Repos/cai-nlptools/node_modules/engine.io-client/lib/transports/polling-xhr.js:310:8)
    at Timeout._onTimeout (/mnt/c/Users/Phil/Source/Repos/cai-nlptools/node_modules/engine.io-client/lib/transports/polling-xhr.js:257:18)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by darrachequesne** [comment]
I'm not able to reproduce, could you check that example please:  https://github.com/darrachequesne/socket.io-fiddle/tree/issue-1151

**Comment by cosminn777** [comment]
I am also getting this!

**Comment by russaa** [comment]
I encountered this too (transport polling & umlauts in message text)

The cause was apparently incompatible versions for client and server:  
 * client: `socket.io-client@2.0.4`
 * server: `socket.io@1.7.4`

updating the server to `socket.io@2.0.4` solved my problem
