### ISSUE TITLE
 Error: Cannot find module 'socket.io'

### ISSUE THREAD

**Issue by Sphinx83** [socketio/socket.io-client#1258]
sudo node rgb.js
internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module 'socket.io'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/rgb/rgb.js:3:10)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)

**Comment by knoxcard** [comment]
This clients socket.io-client not socket.io-server (https://github.com/socketio/socket.io)

Close ticket?

**Comment by darrachequesne** [comment]
For future readers: it sounds like the `socket.io` package (for the server-side) was not installed, please check https://socket.io/docs/v3/server-installation/

**Comment by Moaaz10** [comment]
maybe it helps someone: I accidentally installed "socket-io"(with a dash) instead of "socket.io". Make sure you are installing the write package.
