### ISSUE TITLE
rejectUnathorized is documented wrong

### ISSUE THREAD

**Issue by Hornwitser** [socketio/socket.io-client#1339]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

The `rejectUnathorized` when used on Node is [documented as defaulting to false](https://socket.io/docs/client-api/#new-Manager-url-options) but actually defaults to true (see [relevant line in engine.io-client](https://github.com/socketio/engine.io-client/blob/2847411dd03eab4ab003b50d81c7a44f7bead564/lib/socket.js#L95))

### Steps to reproduce (if the current behaviour is a bug)

Use socket.io-client to connect to an https server with a self signed certificate without specifying `rejectUnauthorized` and observed that the connection fails.  When connecting with `rejectUnathorized` set to false it succeeds.

### Expected behaviour

The documentation should match the implementation.

### Setup
- OS: Linux
- browser: N/A
- socket.io version: 2.2.0

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

When connecting to an https server with a self signed certificate and you do not set rejectUnauthorized to `false` you get this very unhelpful error on the `connect_error` callback.  It would be nice if this said something along the line of "certificate verification failed: self-signed"

    { Error: xhr poll error
        at XHR.Transport.onError (node_modules/engine.io-client/lib/transport.js:67:13)
        at Request.<anonymous> (node_modules/engine.io-client/lib/transports/polling-xhr.js:130:10)
        at Request.Emitter.emit (node_modules/engine.io-client/node_modules/component-emitter/index.js:133:20)
        at Request.onError (node_modules/engine.io-client/lib/transports/polling-xhr.js:311:8)
        at Timeout._onTimeout (node_modules/engine.io-client/lib/transports/polling-xhr.js:258:18)
        at listOnTimeout (internal/timers.js:535:17)
        at processTimers (internal/timers.js:479:7) type: 'TransportError', description: 503 }

**Comment by darrachequesne** [comment]
You are absolutely right, I updated the page here: https://socket.io/docs/v3/client-api/index.html#new-Manager-url-options

Thanks!
