### ISSUE TITLE
Weird characters in socket.io server response causes parser error

### ISSUE THREAD

**Issue by kutluhanmetin** [socketio/socket.io-client#1387]
* [x] report a *bug*

### Current behaviour
I try to connect to a socket.io server with the following code:
```
const io = require('socket.io-client');

const options = {
    extraHeaders: {
        'Cookie': 'token={a-valid-token-for-my-server}'
    },
    rejectUnauthorized: false,
    path: '{custom-path-for-my-server}',
}

const socket = io("https://{my-server-address}", options);
socket.connect()

socket.on('connect_error', function(err){ console.log("connect_error happened:", err) });
```

Connection fails with the following error:
```
Error: server error
    at Socket.onPacket (/Users/kutluhanmetin/Desktop/node-ws-server/node_modules/engine.io-client/lib/socket.js:455:19)
    at XHR.<anonymous> (/Users/kutluhanmetin/Desktop/node-ws-server/node_modules/engine.io-client/lib/socket.js:278:10)
    at XHR.Emitter.emit (/Users/kutluhanmetin/Desktop/node-ws-server/node_modules/component-emitter/index.js:145:20)
    at XHR.Transport.onPacket (/Users/kutluhanmetin/Desktop/node-ws-server/node_modules/engine.io-client/lib/transport.js:149:8)
    at callback (/Users/kutluhanmetin/Desktop/node-ws-server/node_modules/engine.io-client/lib/transports/polling.js:144:10)
    at Object.exports.decodePayload (/Users/kutluhanmetin/Desktop/node-ws-server/node_modules/engine.io-parser/lib/index.js:295:14)
    at XHR.Polling.onData (/Users/kutluhanmetin/Desktop/node-ws-server/node_modules/engine.io-client/lib/transports/polling.js:148:10)
    at Request.<anonymous> (/Users/kutluhanmetin/Desktop/node-ws-server/node_modules/engine.io-client/lib/transports/polling-xhr.js:129:10)
    at Request.Emitter.emit (/Users/kutluhanmetin/Desktop/node-ws-server/node_modules/component-emitter/index.js:145:20)
    at Request.onData (/Users/kutluhanmetin/Desktop/node-ws-server/node_modules/engine.io-client/lib/transports/polling-xhr.js:303:8) {
  code: 'parser error'
}
```

After debugging a bit, I checked the data my server sent and realized that there are weird characters in the beginning of the response message:

<img width="779" alt="Screen Shot 2020-10-17 at 21 55 39" src="https://user-images.githubusercontent.com/5518804/96351707-ec0feb00-10c5-11eb-899b-f0b6b9def282.png">

### Expected behaviour
I expect the response to include `the length of the first message` and `the "open" message type` instead of these weird characters as stated in https://socket.io/docs/internals

### Setup
- OS: Mac OS Catalina 10.15.7
- socket.io client version: 2.3.1

**Comment by darrachequesne** [comment]
Which Socket.IO server are you using? Is it the Javascript implementation (https://github.com/socketio/socket.io)?

**Comment by kutluhanmetin** [comment]
@darrachequesne no, I am using this one: https://hackage.haskell.org/package/socketio

**Comment by darrachequesne** [comment]
@kutluhanmetin could you please open an issue in their issue tracker (here: https://github.com/banacorn/socket.io-haskell) please? (not sure if it is still maintained though)

**Comment by kutluhanmetin** [comment]
I guess it is not a server-side bug @darrachequesne because, when I try it with javascript code embedded in html it works. Can it be a specific problem for NodeJS users?

**Comment by darrachequesne** [comment]
The response of the server looks weird though. Maybe some content encoding issue?

For reference, the Engine.IO protocol is detailed here: https://github.com/socketio/engine.io-protocol/tree/v3

**Comment by dmachacon** [comment]
I also encountered this issue. There's some characters in the beginning of the response of the polling data:

**Comment by jijieoo** [comment]
@dmachacon 
3.x downgrade to 2.3.0。

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by leviluo** [comment]
i miss the small question

error Error: server error
    at Socket.onPacket (socket.js?b2be:393)
    at XHR.Emitter.emit (index.js?75fb:145)
    at XHR.onPacket (transport.js?ccb1:105)
    at callback (polling.js?01b7:98)
    at Array.forEach (<anonymous>)
    at XHR.onData (polling.js?01b7:102)
    at Request.Emitter.emit (index.js?75fb:145)
    at Request.onData (polling-xhr.js?449e:231)
    at Request.onLoad (polling-xhr.js?449e:282)
    at XMLHttpRequest.xhr.onreadystatechange (polling-xhr.js?449e:186) 

How to fix it?

**Comment by leviluo** [comment]
i have the small question:

error Error: server error
    at Socket.onPacket (socket.js?b2be:393)
    at XHR.Emitter.emit (index.js?75fb:145)
    at XHR.onPacket (transport.js?ccb1:105)
    at callback (polling.js?01b7:98)
    at Array.forEach (<anonymous>)
    at XHR.onData (polling.js?01b7:102)
    at Request.Emitter.emit (index.js?75fb:145)
    at Request.onData (polling-xhr.js?449e:231)
    at Request.onLoad (polling-xhr.js?449e:282)
    at XMLHttpRequest.xhr.onreadystatechange (polling-xhr.js?449e:186) 

How to fix it?
