### ISSUE TITLE
TypeError: Cannot set property 'NaN' of undefined

### ISSUE THREAD

**Issue by liesislukas** [socketio/socket.io-client#916]
I haven't updated for few weeks and after npm fresh install i get this:

```
project/node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/polling-xhr.js:245
    Request.requests[this.index] = this;
                                 ^
TypeError: Cannot set property 'NaN' of undefined
at Request.create (project/node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/polling-xhr.js:245:34)
at new Request (project/node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/polling-xhr.js:155:8)
at XHR.request (project/node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/polling-xhr.js:86:10)
at XHR.doPoll (project/node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/polling-xhr.js:116:18)
at XHR.Polling.poll (project/node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/polling.js:118:8)
at XHR.Polling.doOpen (project/node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/polling.js:62:8)
at XHR.Transport.open (project/node_modules/socket.io-client/node_modules/engine.io-client/lib/transport.js:82:10)
at Socket.open (project/node_modules/socket.io-client/node_modules/engine.io-client/lib/socket.js:220:13)
at new Socket (project/node_modules/socket.io-client/node_modules/engine.io-client/lib/socket.js:102:8)
at Socket (project/node_modules/socket.io-client/node_modules/engine.io-client/lib/socket.js:37:41)
```

it happens if i add 
```
let io = require('socket.io')(server);
```
in server.js

i run server.js with serverBabel.js, all it's code: 

```
"use strict"
// All subsequent files required by node with the extensions .es6, .es, .jsx and .js will be transformed by Babel.
require("babel-core/register");

require("./server.js");
```

starting it up with gulp task:

```
gulp.task('live-server', () => {
    var server = gls('./app/server/serverBabel.js', {}, false);
    server.start();
});
```

**Comment by liesislukas** [comment]
I think it was because of jsdom. I've tried to make isomorphic ReactJs app and some modules required document global var. I found in polling-xhr.js that it was checking if document is available and then do stuff that was not available, because my "document" was not real "document".
