### ISSUE TITLE
python socketio client and flask-socketio server

### ISSUE THREAD

**Issue by gaozhidf** [socketio/socket.io-client#938]
File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2222, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 2155, in _find_spec
TypeError: 'NoneType' object is not iterable

It shows TypeError. Because it returns b'OK' not b'ok'

Solution:

For in "....\lib\site-packages\socketIO_client\transports.py", line 97,
  current:
    assert response.content == b'ok'

  change:
    assert response.content == b'ok' or response.content == b'OK'  

Details:

Traceback (most recent call last):
  File "F:/PycharmProjects/test/test_socketio1.py", line 25, in <module>
    piSpace = socketIO.define(Namespace, '/test')
  File "F:\PycharmProjects\test\env\lib\site-packages\socketIO_client\__init__.py", line 358, in define
    self.connect(path)
  File "F:\PycharmProjects\test\env\lib\site-packages\socketIO_client\__init__.py", line 382, in connect
    with_transport_instance)
  File "F:\PycharmProjects\test\env\lib\site-packages\socketIO_client\__init__.py", line 26, in wrap
    return f(*args, **kw)
  File "F:\PycharmProjects\test\env\lib\site-packages\socketIO_client\__init__.py", line 206, in _message
    transport.send_packet(engineIO_packet_type, engineIO_packet_data)
  File "F:\PycharmProjects\test\env\lib\site-packages\socketIO_client\transports.py", line 99, in send_packet
    assert response.content == b'ok'
AssertionError
Exception ignored in: <bound method SocketIO.__del__ of <socketIO_client.SocketIO object at 0x00000000029BDB70>>
Traceback (most recent call last):
  File "F:\PycharmProjects\test\env\lib\site-packages\socketIO_client\__init__.py", line 350, in __del__
  File "F:\PycharmProjects\test\env\lib\site-packages\socketIO_client\__init__.py", line 386, in disconnect
  File "F:\PycharmProjects\test\env\lib\site-packages\socketIO_client\__init__.py", line 184, in _close
  File "F:\PycharmProjects\test\env\lib\site-packages\socketIO_client\transports.py", line 97, in send_packet
  File "F:\PycharmProjects\test\env\lib\site-packages\socketIO_client\transports.py", line 176, in get_response
  File "F:\PycharmProjects\test\env\lib\site-packages\requests\sessions.py", line 511, in post
  File "F:\PycharmProjects\test\env\lib\site-packages\requests\sessions.py", line 454, in request
  File "F:\PycharmProjects\test\env\lib\site-packages\requests\sessions.py", line 369, in prepare_request
  File "F:\PycharmProjects\test\env\lib\site-packages\requests\cookies.py", line 482, in merge_cookies
  File "F:\PycharmProjects\test\env\lib\site-packages\requests\cookies.py", line 310, in update
  File "F:\PycharmProjects\test\env\lib\copy.py", line 97, in copy
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2222, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 2155, in _find_spec
TypeError: 'NoneType' object is not iterable

**Comment by nkzawa** [comment]
It looks this is an issue of `flask-socketio`. Please report this to them.
